src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $login;

    #[ORM\Column(type: 'string', length: 100)]
    private $password;

    #[ORM\Column(type: 'string', length: 100)]
    private $name;

    #[ORM\Column(type: 'string', length: 100)]
    private $first_name;

    #[ORM\Column(type: 'date')]
    private $birth_date;

    #[ORM\Column(type: 'boolean')]
    private $is_admin;

    #[ORM\Column(type: 'boolean')]
    private $is_super_admin;

    #[ORM\OneToMany(mappedBy: 'id_user', targetEntity: ShoppingCart::class, orphanRemoval: true)]
    private $id_shopping_cart;

    public function __construct()
    {
        $this->is_admin = false;
        $this->is_super_admin = false;
        $this->id_shopping_cart = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLogin(): ?string
    {
        return $this->login;
    }

    public function setLogin(string $login): self
    {
        $this->login = $login;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getIsAdmin(): ?bool
    {
        return $this->is_admin;
    }

    public function setIsAdmin(bool $is_admin): self
    {
        $this->is_admin = $is_admin;

        return $this;
    }

    public function getIsSuperAdmin(): ?bool
    {
        return $this->is_super_admin;
    }

    public function setIsSuperAdmin(bool $is_super_admin): self
    {
        $this->is_super_admin = $is_super_admin;

        return $this;
    }

    /**
     * @return Collection<int, ShoppingCart>
     */
    public function getIdShoppingCart(): Collection
    {
        return $this->id_shopping_cart;
    }

    public function addIdShoppingCart(ShoppingCart $idShoppingCart): self
    {
        if (!$this->id_shopping_cart->contains($idShoppingCart)) {
            $this->id_shopping_cart[] = $idShoppingCart;
            $idShoppingCart->setIdUser($this);
        }

        return $this;
    }

    public function removeIdShoppingCart(ShoppingCart $idShoppingCart): self
    {
        if ($this->id_shopping_cart->removeElement($idShoppingCart)) {
            // set the owning side to null (unless already changed)
            if ($idShoppingCart->getIdUser() === $this) {
                $idShoppingCart->setIdUser(null);
            }
        }

        return $this;
    }
}

templates/view/addAdmin.html.twig
{% extends 'layout/layoutPage.html.twig' %}

{% block title %}{{ parent() }} Formulaire d'ajout d'administrateur {% endblock %}


{% block menu %}

    {% set url = path('super_admin_accueil',{'id' : id}) %}
    <ul>
        <li><a href="{{ url }}"> Retour à l'accueil </a></li>
    </ul>

{% endblock %}

{% block vue %}

    {{ form_start(userForm) }}

    {{ form_errors(userForm) }}

    {{ form_rest(userForm) }}

    {{ form_end(userForm) }}

{% endblock %}

templates/view/addProduct.html.twig
{% extends 'layout/layoutPage.html.twig' %}

{% block title %}{{ parent() }} Formulaire d'ajout de produit {% endblock %}


{% block menu %}

    {% set url = path('admin_accueil',{'id' : id}) %}
    <ul>
        <li><a href="{{ url }}"> Retour à l'accueil </a></li>
    </ul>

{% endblock %}

{% block vue %}

    {{ form_start(productForm) }}

    {{ form_errors(productForm) }}

    {{ form_rest(productForm) }}

    {{ form_end(productForm) }}

{% endblock %}

templates/view/adminProductList.html.twig
{% extends 'layout/layoutPage.html.twig' %}

{% block menu %}

    {% set url = path('admin_accueil',{'id' : id}) %}
    <ul>
        <li><a href="{{ url }}"> Retour à l'accueil </a></li>
    </ul>

{% endblock %}

{% block vue %}

    <style>
        table, th, td {
            border: 1px solid;
            text-align: center;
        }
    </style>

    <h2>Table des produits : </h2>

    <table>
        <tr><th>Libellé</th><th>Prix unitaire</th><th>Stock</th><th></th></tr>

        {% for product in products %}
            {{ form_start(shoppingForm) }}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.stock }}</td>
                <td>
                    {{ form_start(shoppingForm) }}
                    {{ form_errors(shoppingForm) }}
                    {{ form_rest(shoppingForm) }}
                    {{ form_end(shoppingForm) }}
                </td>
            </tr>

        {% endfor %}

    </table>
    <button type="submit">Ajouter</button>
{% endblock %}

templates/view/adminUserList.html.twig
{% extends 'layout/layoutPage.html.twig' %}

{% block menu %}

    {% set url = path('admin_accueil',{'id' : id}) %}
    <ul>
        <li><a href="{{ url }}"> Retour à l'accueil </a></li>
    </ul>
{% endblock %}

{% block vue %}

    <style>
        table, th, td {
            border: 1px solid;
            text-align: center;
        }
    </style>

    <h2>Table des utilisateurs : </h2>

    <table>
        <tr><th>id</th><th>login</th><th>password</th><th>name</th><th>first name</th><th>date of birth</th><th>admin</th><th>super-admin</th><th>delete</th></tr>
        {% for user in users %}
            <tr>
                {#{% set param = { 'id_user_delete' : user.id , 'id_current' : id } %}#}
                {% set param = [user.id,id] %}
                {#  {% set urlView = path('admin_view',{'id' : user.id}) %}#}
                {% set urlDelete = path('admin_delete', {'id_current' : id , 'id_delete' : user.id } )%}
                <td>{{ user.id }}</td>
                <td>{{ user.login }}</td>
                <td>{{ user.password|md5 }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.firstName }}</td>
                <td>{{ user.birthDate|format_date }}</td>
                <td>{{ user.isAdmin }}</td>
                <td>{{ user.isSuperAdmin }}</td>
                <td><a href="{{ urlDelete }}">delete</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/view/modifierProfileAdmin.html.twig
{% extends 'layout/layoutPage.html.twig' %}

{% block title %}{{ parent() }} Formulaire de modification du profile {% endblock %}


{% block menu %}

    {% set url = path('super_admin_accueil',{'id' : id}) %}
    <ul>
        <li><a href="{{ url }}"> Retour à l'accueil </a></li>
    </ul>

{% endblock %}

{% block vue %}

    {{ form_start(userForm) }}

    {{ form_errors(userForm) }}

    {{ form_rest(userForm) }}

    {{ form_end(userForm) }}

{% endblock %}

templates/view/service.html.twig
{% extends 'layout/layoutPage.html.twig' %}

{% block title %}{{ parent() }} Formulaire de modification du profile {% endblock %}


{% block menu %}

    {% set url = path('accueil') %}
    <ul>
        <li><a href="{{ url }}"> Retour a l'accueil </a></li>
    </ul>

{% endblock %}

{% block vue %}

    <h1>Service inversion de mot : </h1>

    {{ form_start(serviceForm) }}

    {{ form_errors(serviceForm) }}

    {{ form_rest(serviceForm) }}

    {{ form_end(serviceForm) }}

{% endblock %}

templates/view/userProductList.html.twig
{% extends 'layout/layoutPage.html.twig' %}

{% block menu %}

    {% set url = path('user_accueil',{'id' : id}) %}
    <ul>
        <li><a href="{{ url }}"> Retour à l'accueil </a></li>
    </ul>

{% endblock %}

{% block vue %}

    <style>
        table, th, td {
            border: 1px solid;
            text-align: center;
        }
    </style>

    <h2>Table des produits : </h2>

    <table>
        <tr><th>Libellé</th><th>Prix unitaire</th><th>Stock</th></tr>
        {% for product in products %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.stock }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/view/viewAddAdmin.html.twig
{% extends 'layout/layoutPage.html.twig' %}

{% block title %}{{ parent() }} Formulaire d'ajout d'administrateur {% endblock %}


{% block menu %}

    {% set url = path('super_admin_accueil',{'id' : id}) %}
    <ul>
        <li><a href="{{ url }}"> Retour à l'accueil </a></li>
    </ul>

{% endblock %}

{% block vue %}

    {{ form_start(userForm) }}

    {{ form_errors(userForm) }}

    {{ form_rest(userForm) }}

    {{ form_end(userForm) }}

{% endblock %}

templates/view/viewAddProduct.html.twig
{% extends 'layout/layoutPage.html.twig' %}

{% block title %}{{ parent() }} Formulaire d'ajout de produit {% endblock %}


{% block menu %}

    {% set url = path('admin_accueil',{'id' : id}) %}
    <ul>
        <li><a href="{{ url }}"> Retour à l'accueil </a></li>
    </ul>

{% endblock %}

{% block vue %}

    {{ form_start(productForm) }}

    {{ form_errors(productForm) }}

    {{ form_rest(productForm) }}

    {{ form_end(productForm) }}

{% endblock %}

templates/view/viewAdmin.html.twig
{% extends 'layout/layoutPage.html.twig' %}

{#
Pas de modification particulière dans cette vue, on modifie le template parent donc celui ci n'est pas impacté
#}

{% block title %}{{ parent() }} Hub {% endblock %}

{% block accueil %}
    <h1> Bienvenue {{ firstname }} {{ name }} ! Tu es un {{ type }} </h1>
{% endblock %}

{% block menu %}
    <h2>Panier :</h2>
    <ul>
        {% for panier in paniers %}
            <li>{{ panier }}</li>
        {% endfor %}
    </ul>

    <h2> Liens Administrateur :</h2>

    {% set urlUserList = path('admin_user_list',{'id' : id}) %}
    {% set urlProductList = path('admin_product_list',{'id' : id}) %}
    {% set urlAddProduct = path('admin_add_product',{'id' : id}) %}
    <ul>
        <li><a href="{{ urlUserList }}"> Gestion des utilisateurs </a></li>
        <li><a href="{{ urlProductList }}">Liste des produits disponibles</a></li>
        <li><a href="{{ urlAddProduct }}"> Ajouter un produit dans la base de donnée </a></li>
        <li><a href="https://fr.wikipedia.org/wiki/The Truman Show"> https://fr.wikipedia.org/wiki/The Truman Show </a></li>
    </ul>
{% endblock %}

{% block vue %}
{% endblock %}

templates/view/viewAdminProductList.html.twig
{% extends 'layout/layoutPage.html.twig' %}

{% block menu %}

    {% set url = path('admin_accueil',{'id' : id}) %}
    <ul>
        <li><a href="{{ url }}"> Retour à l'accueil </a></li>
    </ul>

{% endblock %}

{% block vue %}

    <style>
        table, th, td {
            border: 1px solid;
        }
    </style>

    <h2>Table des produits : </h2>

    <table>
        <tr><th>Libellé</th><th>Prix unitaire</th><th>Stock</th></tr>
        {% for product in products %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.stock }}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/view/viewAdminUserList.html.twig
{% extends 'layout/layoutPage.html.twig' %}

{% block menu %}

    {% set url = path('admin_accueil',{'id' : id}) %}
    <ul>
        <li><a href="{{ url }}"> Retour à l'accueil </a></li>
    </ul>
{% endblock %}

{% block vue %}

    <style>
        table, th, td {
            border: 1px solid;
        }
    </style>

    <h2>Table des utilisateurs : </h2>

    <table>
        <tr><th>id</th><th>login</th><th>password</th><th>name</th><th>first name</th><th>date of birth</th><th>admin</th><th>super-admin</th><th>delete</th></tr>
        {% for user in users %}
            <tr>
                {#{% set param = { 'id_user_delete' : user.id , 'id_current' : id } %}#}
                {% set param = [user.id,id] %}
                {#  {% set urlView = path('admin_view',{'id' : user.id}) %}#}
                {% set urlDelete = path('admin_delete', {'id_current' : id , 'id_delete' : user.id } )%}
                <td>{{ user.id }}</td>
                <td>{{ user.login }}</td>
                <td>{{ user.password|md5 }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.firstName }}</td>
                <td>{{ user.birthDate|format_date }}</td>
                <td>{{ user.isAdmin }}</td>
                <td>{{ user.isSuperAdmin }}</td>
                <td><a href="{{ urlDelete }}">delete</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/view/viewCreateOrLogin.html.twig
{% extends 'layout/layoutPage.html.twig' %}

{% block vue %}
    {{ form_start(nonUserForm) }}

    {{ form_errors(nonUserForm) }}

    {{ form_rest(nonUserForm) }}

    {{ form_end(nonUserForm) }}
{% endblock %}

templates/view/viewNonUser.html.twig
{% extends 'layout/layoutPage.html.twig' %}

{% block accueil %}
    <h1> Bienvenue utilisateur inconnu ! </h1>
{% endblock %}

{% block menu %}
    {% set urlCreateAccount = path('createAccount') %}
    {% set urlAuthentification = path('authentification') %}

    <ul>
        <li><a href="{{ urlCreateAccount }}"> Créer un compte </a></li>
        <li><a href="{{ urlAuthentification }}">S'authentifier</a></li>
    </ul>
{% endblock %}